<?php

namespace micetm\conditions\models\constructor\attributes;

use yii\base\Model;
use yii\base\UnknownPropertyException;

class AbstractAttribute extends Model
{
    const STATUS_ACTIVE = 'active';

    const TYPE_DEFAULT = 'default';

    /** @var string */
    public $title;

    /** @var string */
    public $description;

    /** @var string */
    public $type;

    /** @var string */
    public $level;

    /** @var string */
    public $key;

    /** @var string */
    public $status = self::STATUS_ACTIVE;

    /** @var bool  */
    public $multiple = false;

    /** @var array */
    public $comparisons = self::availableComparisons;

    public static $types = [
        'int', 'string', 'bool', 'multiple'
    ];
    public static $statuses = [
        self::STATUS_ACTIVE, 'inactive'
    ];

    const availableComparisons = [
        self::EQUAL_TO_COMPARISON => self::EQUAL_TO_COMPARISON,
        self::GREATER_THAN_COMPARISON => self::GREATER_THAN_COMPARISON,
        self::GREATER_THAN_OR_EQUAL_TO_COMPARISON => self::GREATER_THAN_OR_EQUAL_TO_COMPARISON,
        self::LESS_THAN_COMPARISON => self::LESS_THAN_COMPARISON,
        self::LESS_THAN_OR_EQUAL_TO_COMPARISON => self::LESS_THAN_OR_EQUAL_TO_COMPARISON,
        self::LIKE_COMPARISON => self::LIKE_COMPARISON,
        self::MORE_THAN_ONE_IN_COMPARISON => self::MORE_THAN_ONE_IN_COMPARISON,
    ];

    const EQUAL_TO_COMPARISON = '=';
    const GREATER_THAN_COMPARISON = '>';
    const LESS_THAN_COMPARISON = '<';
    const GREATER_THAN_OR_EQUAL_TO_COMPARISON = '>=';
    const LESS_THAN_OR_EQUAL_TO_COMPARISON = '<=';
    const LIKE_COMPARISON = 'like';
    const MORE_THAN_ONE_IN_COMPARISON = 'in';

    public function rules()
    {
        return [
            ['multiple', 'boolean'],
            [['title', 'description', 'status', 'type', 'level', 'key'], 'string'],
            ['type', 'in', 'range' => self::$types],
            ['status', 'in', 'range' => self::$statuses],
            ['comparisons', 'each', 'rule' => ['in', 'range' => self::availableComparisons]],
            ['data', 'safe'],
        ];
    }

    public function __set($name, $value)
    {
        try {
            return parent::__set($name, $value); // TODO: Change the autogenerated stub
        } catch (UnknownPropertyException $exception) {

        }
    }
}